apiVersion: v1
kind: Pod
metadata:
  name: karpenter-test
spec:
  containers:
  - name: pause
    image: public.ecr.aws/eks-distro/kubernetes/pause:3.9
    resources:
      requests:
        cpu: "2"
        memory: "1Gi"
  tolerations:
  - key: "karpenter.sh/provisioner-name"
    operator: "Exists"

