auth:
  existingSecret: mysql-db-secret
  username: "flaskapp"
  


initdbScripts:
    my_init_script.sql: |
      CREATE DATABASE IF NOT EXISTS exampleDb;
      FLUSH PRIVILEGES;
      USE exampleDb;
      CREATE TABLE IF NOT EXISTS people (
      id int(11) NOT NULL AUTO_INCREMENT,
      firstname varchar(100) NOT NULL,
      lastname varchar(100) NOT NULL,
      age int(11) NOT NULL,
      address varchar(100) NOT NULL,
      workplace varchar(100) NOT NULL,
      PRIMARY KEY (`id`),
      UNIQUE KEY `id` (`id`)
      ) ENGINE=MyISAM AUTO_INCREMENT=10001;
      INSERT INTO people (firstname, lastname, age, address, workplace)
      VALUES ('John', 'Doe', 30, '123 Main St, New York, NY 10030', 'Google'),('Jane', 'Doe', 28, '123 Main St, New York, NY 10030', 'Microsoft'),('Jack', 'Doe', 25, '123 Main St, New York, NY 10030', 'Amazon');
      GRANT ALL PRIVILEGES ON exampleDb.* TO 'flaskapp'@'%' WITH GRANT OPTION;
      FLUSH PRIVILEGES;
      



# GRANT ALL PRIVILEGES ON exampleDb TO 'flaskapp'@'%' IDENTIFIED BY 'flaskapp' WITH GRANT OPTION;
#       FLUSH PRIVILEGES;

#       USE exampleDb;

#       CREATE TABLE IF NOT EXISTS `people` (
#         `id` int(11) NOT NULL AUTO_INCREMENT,
#         `firstname` varchar(100) NOT NULL,
#         `lastname` varchar(100) NOT NULL,
#         `age` int(11) NOT NULL,
#         `address` varchar(100) NOT NULL,
#         `workplace` varchar(100) NOT NULL,
#         PRIMARY KEY (`id`),
#         UNIQUE KEY `id` (`id`)
#       ) ENGINE=MyISAM AUTO_INCREMENT=10001;


#       INSERT INTO `people` (`firstname`, `lastname`, `age`, `address`, `workplace`) VALUES
#       ('John', 'Doe', 30, '123 Main St, New York, NY 10030', 'Google'),
#       ('Jane', 'Doe', 28, '123 Main St, New York, NY 10030', 'Microsoft'),
#       ('Jack', 'Doe', 25, '123 Main St, New York, NY 10030', 'Amazon');

# primary:
#   initdbScripts:
#     my_init_script.sh: |
#       mysql -uroot -p"$(MYSQL_ROOT_PASSWORD_FILE)" -e CREATE DATABASE IF NOT EXISTS exampleDb;
#       mysql -uroot -p"$(MYSQL_ROOT_PASSWORD_FILE)" -e GRANT ALL PRIVILEGES ON `exampleDb` TO 'flaskapp'@'%' IDENTIFIED BY 'flaskapp' WITH GRANT OPTION;
#       mysql -uroot -p"$(MYSQL_ROOT_PASSWORD_FILE)" -e FLUSH PRIVILEGES;
#       mysql -uroot -p"$(MYSQL_ROOT_PASSWORD_FILE)" -e CREATE TABLE IF NOT EXISTS `people` (`id` int(11) NOT NULL AUTO_INCREMENT,`firstname` varchar(100) NOT NULL,`lastname` varchar(100) NOT NULL,`age` int(11) NOT NULL,`address` varchar(100) NOT NULL,`workplace` varchar(100) NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `id` (`id`)) ENGINE=MyISAM AUTO_INCREMENT=10001;
#       mysql -uroot -p"$(MYSQL_ROOT_PASSWORD_FILE)" -e INSERT INTO `people` (`firstname`, `lastname`, `age`, `address`, `workplace`) VALUES('John', 'Doe', 30, '123 Main St, New York, NY 10030', 'Google'),('Jane', 'Doe', 28, '123 Main St, New York, NY 10030', 'Microsoft'),('Jack', 'Doe', 25, '123 Main St, New York, NY 10030', 'Amazon');
#     ini.sql: |
#       CREATE DATABASE IF NOT EXISTS exampleDb;
#       GRANT ALL PRIVILEGES ON exampleDb.* TO 'flaskapp'@'%' IDENTIFIED BY 'flaskapp' WITH GRANT OPTION;
#       FLUSH PRIVILEGES;

#       USE exampleDb;

#       CREATE TABLE IF NOT EXISTS people (
#         id INT AUTO_INCREMENT PRIMARY KEY,
#         firstname VARCHAR(100) NOT NULL,
#         lastname VARCHAR(100) NOT NULL,
#         age INT NOT NULL,
#         address VARCHAR(100) NOT NULL,
#         workplace VARCHAR(100) NOT NULL
#       ) ENGINE=InnoDB AUTO_INCREMENT=10001;

#       INSERT INTO people (firstname, lastname, age, address, workplace) VALUES
#       ('John', 'Doe', 30, '123 Main St, New York, NY 10030', 'Google'),
#       ('Jane', 'Doe', 28, '123 Main St, New York, NY 10030', 'Microsoft'),
#       ('Jack', 'Doe', 25, '123 Main St, New York, NY 10030', 'Amazon');

# initdbScripts:
#   my_init_script.sh: |
#     #!/bin/bash
#     if [[ $(hostname) == *primary* ]]; then
#       echo "Primary node"
#       password_aux="${MYSQL_ROOT_PASSWORD:-}"
#       if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
#           password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
#       fi
      
#       # Create database and user
#       mysql -uroot -p"$password_aux" 
#       CREATE DATABASE IF NOT EXISTS 'exampleDb';
#     else
#       echo "Secondary node"
#     fi

# initdbScripts:
#   my_init_script.sh: |
#     #!/bin/bash
#     if [[ $(hostname) == *primary* ]]; then
#       echo "Primary node"
#       password_aux="${MYSQL_ROOT_PASSWORD:-}"
#       if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
#           password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
#       fi
#       mysql -P 3306 -uroot -p"$password_aux" -e "create database new_database";
#     else
#       echo "Secondary node"
#     fi





# initdbScripts:
#   my_init_script.sh: |
#     #!/bin/bash
#     if [[ $(hostname) == *primary* ]]; then
#       echo "Primary node"
#       password_aux="${MYSQL_ROOT_PASSWORD:-}"
#       if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
#           password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
#       fi
#       mysql -P 3306 -uroot -p"$password_aux" <<'EOF'
#         CREATE DATABASE IF NOT EXISTS `exampleDb`;
#         GRANT ALL PRIVILEGES ON `exampleDb`.* TO 'flaskapp'@'%' IDENTIFIED BY 'flaskapp' WITH GRANT OPTION;
#         FLUSH PRIVILEGES;
        
#         USE exampleDb;
        
#         CREATE TABLE IF NOT EXISTS `people` (
#           `id` int(11) NOT NULL AUTO_INCREMENT,
#           `firstname` varchar(100) NOT NULL,
#           `lastname` varchar(100) NOT NULL,
#           `age` int(11) NOT NULL,
#           `address` varchar(100) NOT NULL,
#           `workplace` varchar(100) NOT NULL,
#           PRIMARY KEY (`id`)
#         ) ENGINE=MyISAM AUTO_INCREMENT=10001;
        
#         INSERT INTO `people` (`firstname`, `lastname`, `age`, `address`, `workplace`) VALUES
#           ('John', 'Doe', 30, '123 Main St, New York, NY 10030', 'Google'),
#           ('Jane', 'Doe', 28, '123 Main St, New York, NY 10030', 'Microsoft'),
#           ('Jack', 'Doe', 25, '123 Main St, New York, NY 10030', 'Amazon');
#           EOF
#     else
#       echo "Secondary node"
#     fi


# -e CREATE DATABASE IF NOT EXISTS exampleDb;
#       mysql -uroot -p"$(MYSQL_ROOT_PASSWORD_FILE)" -e GRANT ALL PRIVILEGES ON `exampleDb` TO 'flaskapp'@'%' IDENTIFIED BY 'flaskapp' WITH GRANT OPTION;
#       mysql -uroot -p"$(MYSQL_ROOT_PASSWORD_FILE)" -e FLUSH PRIVILEGES;
#       mysql -uroot -p"$(MYSQL_ROOT_PASSWORD_FILE)" -e CREATE TABLE IF NOT EXISTS `people` (`id` int(11) NOT NULL AUTO_INCREMENT,`firstname` varchar(100) NOT NULL,`lastname` varchar(100) NOT NULL,`age` int(11) NOT NULL,`address` varchar(100) NOT NULL,`workplace` varchar(100) NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `id` (`id`)) ENGINE=MyISAM AUTO_INCREMENT=10001;
#       mysql -uroot -p"$(MYSQL_ROOT_PASSWORD_FILE)" -e INSERT INTO `people` (`firstname`, `lastname`, `age`, `address`, `workplace`) VALUES('John', 'Doe', 30, '123 Main St, New York, NY 10030', 'Google'),('Jane', 'Doe', 28, '123 Main St, New York, NY 10030', 'Microsoft'),('Jack', 'Doe', 25, '123 Main St, New York, NY 10030', 'Amazon');
      # INSERT INTO `people` (`firstname`, `lastname`, `age`, `address`, `workplace`) VALUES('John', 'Doe', 30, '123 Main St, New York, NY 10030', 'Google'),('Jane', 'Doe', 28, '123 Main St, New York, NY 10030', 'Microsoft'),('Jack', 'Doe', 25, '123 Main St, New York, NY 10030', 'Amazon');