# File: helm/karpenter/values.yaml
controller:
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1Gi
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

# Required AWS settings that were missing
settings:
  clusterName: "poc-us-east-1-eks"
  clusterEndpoint: ""  # Will be filled by the cluster endpoint
  defaultInstanceProfile: ""  # Will be filled by the instance profile name

serviceAccount:
  create: true
  name: "karpenter"
  annotations:
    eks.amazonaws.com/role-arn: ""  # Will be filled by the role ARN

rbac:
  create: true

logLevel: "debug"

nodePoolDefaults:
  requirements:
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
    - key: kubernetes.io/os
      operator: In
      values: ["linux"]
  limits:
    cpu: 1000