# File: helm/karpenter/values.yaml
controller:
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1Gi
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

# Required AWS settings that were missing
settings:
  clusterName: "poc-us-east-1-eks"
  clusterEndpoint: "https://A9EE0174D85C4E795AAED1B2216C8B4C.gr7.us-east-1.eks.amazonaws.com"  # Updated with correct endpoint
  defaultInstanceProfile: "KarpenterNodeInstanceProfile-poc-us-east-1-eks"

serviceAccount:
  create: true
  name: "karpenter"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::010575877879:role/KarpenterController-poc-us-east-1-eks"  # Added role ARN

rbac:
  create: true

logLevel: "debug"

nodePoolDefaults:
  requirements:
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
    - key: kubernetes.io/os
      operator: In
      values: ["linux"]
  limits:
    cpu: 1000